### ISSUE TITLE
Owners of PRs belonging to multiple projects aren't recognised

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/parity-processbot#161]
See https://github.com/paritytech/substrate/pull/5814#issuecomment-621053602, which belongs to the projects `Stabilizing` and `Client`, where the bot didn't merge although the owner of `Client` (me) reviewed the PR.

To clarify:
1. a PR can have many projects it belongs to
2. if no owner of a project is known, the project should be ignored by the bot
3. for all projects with known owners, the owner should sign off.
4. If someone asks the bot to merge, but it can't because of that condition it should mention the missing owners and assign them the PR.

**Comment by sjeohp** [comment]
This is implemented and should have been closed some weeks ago.
