### ISSUE TITLE
Checks rescheduled via gitlab are not reflected in github responses

### ISSUE THREAD

**Issue by sjeohp** [paritytech/parity-processbot#206]

**Comment by joao-paulo-parity** [comment]
@TriplEight do you have any idea of what this is?

**Comment by TriplEight** [comment]
can only guess. Maybe when the bot has already answered on some command with a comment (with a failure), restarting the underlying job does not edit the message or write a new one? Is it desirable behaviour?

**Comment by joao-paulo-parity** [comment]
> can only guess. Maybe when the bot has already answered on some command with a comment (with a failure), restarting the underlying job does not edit the message or write a new one? Is it desirable behaviour?

I don't think that's what this feature is about. Either way, we don't have a way of actually knowing what this really meant at the moment. I'll be closing this and open a new issue when we have a convincing report of it happening and how it happens exactly.
