### ISSUE TITLE
Ensure audit-related labels on certain PRs

### ISSUE THREAD

**Issue by haikoschol** [paritytech/parity-processbot#221]
Desired behaviour: PRs which touch `frame/*` code cannot be merged unless tagged with {`insubstantial`, `nicetohaveaudit`}, `needsaudit` or `audited`.

**Comment by haikoschol** [comment]
Also consider requiring that team leads sign off on the `insubstantial` label.

**Comment by joao-paulo-parity** [comment]
Asked on Matrix about requirements' updates and who requested this. Blocked until we get a response.

**Comment by joao-paulo-parity** [comment]
Update: [labels are checked on CI](https://github.com/paritytech/polkadot/blob/master/scripts/github/check_labels.sh#L18) but the proposal here is more specific, based on which files have changed. Need to discuss with the CI team to see if it's better to do that on CI or here.

**Comment by joao-paulo-parity** [comment]
There's some file-based checking already happening with Github Actions: https://github.com/paritytech/polkadot/blob/ea6f7303491299a7cd21cf93535757ae691bd18c/scripts/github/check_labels.sh#L57.

The same check could be implemented here for redundancy, as a fail-safe, but it's not a trivial change. This request has no owner and therefore we don't know who to ask for measuring its importance to decide if the effort is warranted.

Given the aforementioned circumstances, we assume the Github Actions check is enough, thus there's no motivation to implement it here. @s3krit says they can change the action's code if the check needs to be improved.

Closing.
