### ISSUE TITLE
Reduce access permissions on Gitlab

### ISSUE THREAD

**Issue by haikoschol** [paritytech/parity-processbot#226]
The bot needs to start a CI job on Gitlab for the `burnin` command. Right now it uses a personal access token (in my account), with scope "api". Investigate switching the API interaction to the [Pipelines Trigger API](https://docs.gitlab.com/ee/ci/triggers/) together with a more restrictive token.

**Comment by joao-paulo-parity** [comment]
Burn-in request flows are to be redesigned as per https://github.com/paritytech/parity-processbot/pull/241#issuecomment-900899437, thus this issue doesn't make sense anymore
