### ISSUE TITLE
burnin: Unexpected CI job status "created"

### ISSUE THREAD

**Issue by haikoschol** [paritytech/parity-processbot#227]
[This](https://github.com/paritytech/polkadot-for-processbot-staging/pull/3#issuecomment-708393903) happens for pipelines with long running jobs that need to finish before the manual CI job triggered by the bot becomes available. Between the pipeline starting and the job becoming available, it is in state `created`, which is not handled by processbot yet. It would need to be added [here](https://github.com/paritytech/parity-processbot/blob/master/src/gitlab_bot.rs#L63) such that the bot responds with a useful message (e.g. "CI job for burn-in deployment is not available yet. Please try again when previous jobs in the pipeline have succeeded.").

**Comment by JacksonIsaac** [comment]
Working on this :)

**Comment by haikoschol** [comment]
closed in favor of #240
