### ISSUE TITLE
Pre-merge pipelines.

### ISSUE THREAD

**Issue by TriplEight** [paritytech/parity-processbot#229]
# The Main benefits include

- reduce the amont of CI jobs performed each `git push`
- push some rarely-needed jobs being executed just once, right before the merge. (Jobs such as `cargo audit`, licensing, vulnerability, duped deps, fuzzing, performance regression, chaos, e2e, other long-running tests)
- run the whole pipeline merged with master on a temporary branch, to make sure `master` stays evergreen
- have a [merge queue](https://github.com/bors-rs/bors#a-merge-bot-for-github-pull-requests) 
- merge automatically if conditions (approved and green) are met

## exactly as [Bors](https://github.com/bors-ng/bors-ng), but we can't use it for open source projects

_See this comment in [ink! discussion](https://github.com/paritytech/ink/issues/535#issuecomment-714391457) about the reasons._

Good description, nothing to add [here](https://bors.tech/). And a [longer read](https://graydon2.dreamwidth.org/1597.html), more about the concepts.
Bors commands [reference](https://bors.tech/documentation/).
Inspired by the [Bors-rs](https://github.com/graydon/bors) written in Rust, used by [Rust-lang](https://github.com/rust-lang/rust/pull/12003) since forever.
New Rust [implementation](https://github.com/bors-rs/bors), might become a source of inspiration.

## Alternatives

1. Set the jobs to branch off master and run there after merge. Additional effort is that it would be nice from the failed job to file an issue with a link to the failed pipeline, PR hash, ping someone.

2. Semi-manual job, not appealing
  - make the fuzzing job always manual, so the PR author will go to GitLab UI and push that play button when needed.
  - make this job obligatory for merging.

    The former can be automated variously: `parity-processbot` to read some certain github comment (or some certain label) and trigger the manual job, receive the status. Or trigger it via GitLab API any other way.

    The downside here will be that **all** the not-ready to merge jobs will have the yellow status (waiting for the obligatory job to report status) in GitHub.

**Comment by TriplEight** [comment]
Shouldn't have assigned it, wanted to mention those who might be interested: @dvdplm , @gnunicorn , @s3krit , @gabreal , @cmichi

**Comment by joao-paulo-parity** [comment]
HackerNews discussion about relevant tools: https://news.ycombinator.com/item?id=21584144

That's where I found Kodiak's comparison table: https://kodiakhq.com/docs/prior-art-and-alternatives

I haven't gone through all the references there. Might be worth it to explore more later.

**Comment by ordian** [comment]
there is also https://github.com/mergifyio/mergify-engine which is used by https://github.com/paritytech/smoldot

**Comment by joao-paulo-parity** [comment]
As per https://github.com/paritytech/opstooling/issues/65 we don't plan to implement pre-merge pipelines on processbot directly, so I'm closing this
