### ISSUE TITLE
Parse Matrix messages for interactions on Github Features

### ISSUE THREAD

**Issue by sjeohp** [paritytech/parity-processbot#23]
https://github.com/paritytech/parity-processbot/issues/23#issuecomment-813393683

**Comment by joao-paulo-parity** [comment]
Needs some description of what the feature does and what it's used for. @lovelaced do you know what this is?

**Comment by lovelaced** [comment]
I think originally the processbot was going to have some level of Matrix interaction (hence the matrix inclusion in the codebase), but I'm not sure what the design was intended to be or if it ever really came to fruition, and I imagine this can be closed unless anyone still has any input on this functionality. Some historical screenshots:

![2021-04-05-152734_1021x304_scrot](https://user-images.githubusercontent.com/8581604/113578724-8c7dab80-9623-11eb-8bcc-3b377a036627.png)
![2021-04-05-152701_816x195_scrot](https://user-images.githubusercontent.com/8581604/113578725-8d164200-9623-11eb-933c-30a0d335819b.png)

**Comment by joao-paulo-parity** [comment]
> this can be closed unless anyone still has any input on this functionality

I've never received any request for Matrix interaction, nor heard about someone wanting to have it. I'll leave this issue open as a reminder to remove the Matrix/Bamboo code as it's just burden at the moment.
