### ISSUE TITLE
Add a link to branch on GitLab to the burn-in bot.

### ISSUE THREAD

**Issue by TriplEight** [paritytech/parity-processbot#232]
i.e. paritytech/polkadot#1776 and the added link would be https://gitlab.parity.io/parity/polkadot/-/commits/1776, which always has the same number.

So the one who does the deployment opens the latest pipeline and pushes the manual build button.

**Comment by haikoschol** [comment]
@TriplEight What do you mean with adding the link to the bot? Where would the link be displayed? When processbot is used for burn-ins, the manual build job will be started automatically. Does this suggestion still apply in that case?

**Comment by TriplEight** [comment]
I thought that when the job is started automatically, the bot would post about it in some matrix channel. And it would be handy to have a direct link to the pipeline.

**Comment by haikoschol** [comment]
> I thought that when the job is started automatically, the bot would post about it in some matrix channel. And it would be handy to have a direct link to the pipeline.

That's exactly what the bot does:
- find the `build-linux-release` job and start it
- post a notification as comment on the PR, with a link to the CI job (like [here](https://github.com/paritytech/polkadot-for-processbot-staging/pull/2#issuecomment-697360098) in staging)
- post a notification and potentially a detailed error message in a matrix channel

It does not post a link to the branch on Gitlab, just to the CI job though.
