### ISSUE TITLE
Ignores allow_failure

### ISSUE THREAD

**Issue by TriplEight** [paritytech/parity-processbot#242]
Processbot has [refused](https://github.com/paritytech/substrate/pull/8086#issuecomment-783204222) to merge the PR.

Evidently, `cargo-deny` was the only job failed in the matching [pipeline](https://gitlab.parity.io/parity/substrate/-/pipelines/125005). This job is [allowed to fail](https://github.com/paritytech/substrate/blob/master/.gitlab-ci.yml#L225) and not required by GitHub to pass.
![image](https://user-images.githubusercontent.com/17856421/108700675-3f2bfb80-7507-11eb-8614-5bc5684eb707.png)
This would cause GitHub to reject the merge though.

Another problem is that this job has appeared in this pipeline in the first place, it's triggered by [changes](https://github.com/paritytech/substrate/blob/master/.gitlab-ci.yml#L205-L207) in the manifests or a lock file, but GitLab counts rebase diffs as changed files and it seems fair (but not really obvious) that the job runs here.

I've found a  [piece of code](https://github.com/paritytech/parity-processbot/blob/dee4d2479cdbbf835160b26712203455b39eb21b/src/webhook.rs#L1322-L1331) that's responsible to identify if the job is allowed to fail, but not knowing where to see the logs I wouldn't attempt fixing it.

This is pretty important, I think I'll have to skip the `cargo-deny` check for PRs until it's resolved.

**Comment by joao-paulo-parity** [comment]
The aforementioned `status_failure_allowed` function is not being used anywhere currently.

This also requires a change in vanity-service ([#8](https://gitlab.parity.io/parity/websites/vanity-service/-/issues/8)).

**Comment by joao-paulo-parity** [comment]
The vanity-service shortcoming is not an absolute blocker since it's possible to hardcode the `continuous-integration/gitlab-cargo-deny` skip in the code (although that's obviously brittle and subpar); it's arguably fine as a stopgap measure.
