### ISSUE TITLE
Parse "enum-like" fields as string, then implement API for matching it

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/parity-processbot#245]
As discussed in https://github.com/paritytech/parity-processbot/issues/219, decoding the "enum-like" fields from the API types has some problems

- Incurs unwarranted parsing errors due to untracked variants
- Adds extra burden to keep up with the API variants whenever Github decides to change it

#244 suggests a less error-prone interface like the following

```rust
enum EventAction {
  Foo
}

struct Event {
  action: String // String instead of EventAction; purposefully private
}

impl Event {
  pub fn is_action(&self, action: EventAction) -> bool {
    self.action == action.to_string()
  }
}
```

Using `[variant].to_string()` is less error-prone than working with literal strings since the latter is subject to typos.

**Comment by ordian** [comment]
I have an alternative suggestion, that doesn't require a string allocation: https://github.com/paritytech/parity-processbot/pull/244#discussion_r591245983

**Comment by joao-paulo-parity** [comment]
> I have an alternative suggestion, that doesn't require a string allocation: [#244 (comment)](https://github.com/paritytech/parity-processbot/pull/244#discussion_r591245983)

Seems good, although I'd argue it's more error-prone since it requires the implementer to track if those annotations are put in the right places. Let's go with that, though.

**Comment by ordian** [comment]
> > I have an alternative suggestion, that doesn't require a string allocation: [#244 (comment)](https://github.com/paritytech/parity-processbot/pull/244#discussion_r591245983)
> 
> Seems good, although I'd argue it's more error-prone since it requires the implementer to track if those annotations are put in the right places. Let's go with that, though.

Yes, we need more tests ;)
