### ISSUE TITLE
Companion PR update flow should be better controlled

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/parity-processbot#250]
https://github.com/paritytech/polkadot/pull/2504 showcases a bad scenario for the Companion Update Flow.

The "Update Substrate" commit was made when the pipeline for that PR was not passing. This is ill-advised because

- The work might be in-progress
- The failing checks might have nothing to do with Substrate being outdated
- It disrupts the developer's branch before the PR is ready to merge (i.e. when all checks would be passing)

Furthermore, this flow should not automatically trigger a merge as only the relevant code owners should explicitly signal when it's time to merge.

https://github.com/paritytech/parity-processbot/blob/5e2e6b3b7486a4faadedf285b50e7c3bbfcaea54/src/webhook.rs#L1263-L1269

---

Here's the proposed behavior after the changes:

- No longer attempt automatic merge on the behalf of the PR owner
- Attempt to create the master merge commit **and then** Substate Update commit only after the developer says `bot merge`

**Comment by ordian** [comment]
As mentioned in https://github.com/paritytech/parity-processbot/issues/236#issuecomment-796716221, this can't happen, because of this check:
https://github.com/paritytech/substrate/blob/6ac86d545f6da8e4afc373dc0876c3e7ba79e51b/.maintain/gitlab/check_polkadot_companion_build.sh#L88-L96

**Comment by joao-paulo-parity** [comment]
I'll try to rephrase this issue another way

# Problem

- The pipeline for https://github.com/paritytech/polkadot/pull/2504/commits/1df4e8b5d4f800ff2798a5b092c659ea64cd26e8 was failing
- The "Update Substrate" (https://github.com/paritytech/polkadot/pull/2504/commits/f80605ec42beae5c180d1b6fd9e8645b72158c3d) commit was made regardless

Regarding the above, according to this proposal

- The commit should not have been made when the pipeline was not passing
- The compulsive merge that follows said commit should not be triggered without the developer's consent

# Proposed solution

No longer create the commit when the Substrate PR is merged. Instead, wait until the developer says `bot merge`, then perform two steps *if necessary*.

1. Create master merge commit
2. Update Substrate

With this solution, the "compulsive merge" behavior would also be dealt with since the action is always started imperatively from the developer.

It's also possible that some MR might sneak in right after the command, which would make the branch outdated again. This can be dealt in #236.

@ordian I might be planning this out under failing assumptions, in which case you're welcome to point out what's wrong. I'm only rephrasing it this way because I thought the concerns you were bringing up in the other issue had nothing to do with the problems I'm listing above, but I might be wrong.

**Comment by ordian** [comment]
> @ordian I might be planning this out under failing assumptions, in which case you're welcome to point out what's wrong. I'm only rephrasing it this way because I thought the concerns you were bringing up in the other issue had nothing to do with the problems I'm listing above, but I might be wrong.

Yes, I know our current companion build system is very confusing, but here is how it works:
* polkadot is built upon substrate
* when someone creates a substrate PR, CI checks whether updating polkadot to this new substrate branch will require any changes, if it does, it label it with a `A7-needspolkadotpr` label
* the author (or someone else) of the substrate PR is required to create a companion PR in polkadot that will make those changes
* NOTE: the CI on the polkadot companion is expected to fail, because it uses an old commit of substrate
* but CI on substrate side will check that *if* we update substrate properly, the build will pass (see the link above)
* so after issuing a merge command on the substrate side, it will only succeed if the companion is buildable (modulo substrate update)
* after substrate PR is merged by bot, it will create an `Update Substrate` commit, which is expected to succeed, because it was checked on the substrate side

As you can see, the last step is very fragile due to race conditions and `Cargo.lock` being prone to merge conflicts.
We could entirely rethink how it's done, but that's would be a large amount of work.
But a simpler solution would be to detect if the head ref has changed before and after the `Update Substrate` commit and regenerate it or revert it and create another commit. Just some ideas, I don't really know what'd be ideal.

**Comment by joao-paulo-parity** [comment]
That's a really helpful walk-through.

I understand now that having the status failing is not necessarily a bad sign, although I still have similar ideas about how I would like to change the flow to work around the problem with more predictability. I'll take some time to work on the testing infrastructure for this project and them come up with a tested implementation for my proposal.

My intention is to make some changes in the PR <-> bot interaction and the behavior towards companion PRs, not a full "rework" of the system.

**Comment by ordian** [comment]
An alternative solution for the race condition problem would be that the merge command would actually not push the commit straight away, but put it in the queue, and pops from queue only when the oldest PR that was requested to be merged was merged.

It has two downsides
* it requires a long-running process/server to maintain the global queue
* will only work as expected if all PRs are merged by bot

**Comment by ordian** [comment]
Another problem that could be solved with a global queue:
* deadlock https://github.com/paritytech/polkadot/pull/2610#issuecomment-800252606

that would require not merging a substrate PR with a companion until there are no unmerged companions left.

**Comment by joao-paulo-parity** [comment]
Having a queue will be relevant for #229 so it's something we should look to implement. Prior art: [Bors' queue](https://bors.rust-lang.org/queue/rust).

Currently the Bot simply blocks until each JSON payload is fully processed.

https://github.com/paritytech/parity-processbot/blob/40807b2fe0695437a4907183befd427b1e55d561/src/webhook.rs#L58

Once the queue is implemented, there should be tests to verify that the payloads are processed in the order they are received even if such guarantees are given by the concurrency construct as their usage is subject to change over time.

Denying a Substrate merge if the companion is not passing sounds like a good idea to me but I don't know if it would be limiting.

Ordering the companion merge order by the Substrate merge order is also a good idea - it's what happens most of the time already since the companion update is called right after the merge, although there are no guarantees in case 2+ companions are racing.

**Comment by joao-paulo-parity** [comment]
Closing as the underlying assumptions made for this ticket doesn't match how the Companion Build System is supposed to work
