### ISSUE TITLE
Do not index serialized pull requests by commit SHA alone

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/parity-processbot#273]
Problem: Serialized pull requests are indexed in the database by their HEAD commit sha alone

https://github.com/paritytech/parity-processbot/blob/7bc28b0b6c765e48f7cdeb4b502c1987420ba4c1/src/webhook.rs#L1136

They instead should be indexed by a truly unique identifier as commit SHAs are not globally unique:

- Two different repositories might have PRs with the same SHA, although it's very unlikely for that to happen.
- Two different pull requests might have the same HEAD SHA, although, again, this does not come up in practice

Solution: Serialize the pull request by a globally unique key such as `repository + sha`, or `repository + pr_id`, etc

**Comment by joao-paulo-parity** [comment]
Updated: it's not straightforward to change it. Ideally we'd index it by some pull request identifier, but Github Status Webhook Payloads do not report the Pull Request a status is associated to.

https://github.com/octokit/webhooks/blob/master/payload-examples/api.github.com/status/payload.json

Therefore it'd be necessary to do an extra API call for each SHA and figure out which PR it refers to.

Alternatively the indexing strategy could be changed for it to be a mapping of `[PullRequest] => { ..., SHA }`, then we'd iterate on the values instead of the keys for identifying the pull request; have to see if that's viable for RocksDB.

**Comment by haikoschol** [comment]
> have to see if that's viable for RocksDB

Slightly OT for this issue, but have you considered switching to something more reasonable like Redis or PostgreSQL? It's probably a bit of work and there's lots of high priority stuff in front of it.

If you're looking for a small codebase that has PostgreSQL including migrations set up in Rust using [Diesel](https://diesel.rs/), have a look at [staking-indexer](https://gitlab.parity.io/parity/staking-indexer).

**Comment by joao-paulo-parity** [comment]
I appreciate the simplicity of RocksDB and it serves the current needs well. I'd consider moving to another disk-based key-value storage if it had better features *and* if I were needing those features, before considering the switch to a relational database.

The database is only used for tracking which pull requests are pending by their HEAD commit SHA, thus there's no need for a "table" concept and key-value storage is enough. It's not the end of the world if something vanishes, as long as the storage is *somewhat* reliable between container restarts. It's definitely not something that needs to be backed-up, either.

Overall I'm satisfied with RocksDB because it's simple. We'll see if it needs to change to something else for this feature.

Thanks for the input. :-)

**Comment by joao-paulo-parity** [comment]
Note: The status' payload includes the repository as noted [here](https://github.com/paritytech/parity-processbot/blob/4be550c403e4225e37bc085ed74c8dba8deaadfb/src/github.rs#L372). A combination of repository id + SHA for the key will be enough.
