### ISSUE TITLE
Add /health endpoint

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/parity-processbot#288]
# Implementation

- Implement `/health` endpoint
- Add `livenessProbe` and `readinessProbe` to the Helm chart

# Context

https://github.com/paritytech/devops/issues/567#issuecomment-831975095

> The liveness and readiness checks happen inside the cluster, directly on the pod(s). So it's sufficient to add an endpoint for each in the Rust code. However, liveness and readiness checks can be tricky to get right. It's been a long time since I fell into those pitfalls, so I don't remember much more than that. This article has some background info: https://srcco.de/posts/kubernetes-liveness-probes-are-dangerous.html Might be dated but should give you an idea what to look out for.

https://github.com/paritytech/devops/issues/567#issuecomment-831933048

> It wouldn't be helpful imo if there would be an additional ingress only for monitoring. The health checks (live and ready) should rather reflect the pods well being itself. for instance if it fails to do what it is supposed to do health checks should fail if potentially a redeployment would solve the isssue.

**Comment by azerella** [comment]
This will be quite a big feature considering we don't currently support a REST API. I wonder if we can just add a Prom probe on an interval for a _special_ web hook POST - might be a lot quicker than creating a REST API solely for a health check and it's technically more accurate as a health check.

This health check doesn't _really_ make sense here as _technically_ the Webhook is running on a separate HTTP server.
