### ISSUE TITLE
"bot rebase" is broken / improve messaging when branch is up-to-date

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/parity-processbot#385]
https://github.com/paritytech/substrate/pull/11448#issuecomment-1130064401

https://github.com/paritytech/parity-processbot/issues/385#issuecomment-1130176317

**Comment by mordamax** [comment]
@joao-paulo-parity what exactly is this broken? I see bot responded there, could you please add more details
Thansk!

**Comment by joao-paulo-parity** [comment]
In https://github.com/paritytech/parity-processbot#commands-, `bot rebase` is advertised as

> bot rebase: create a merge commit from origin/master into the PR

The bot posted a comment but the command didn't do what it's supposed to do, hence why it's broken

**Comment by joao-paulo-parity** [comment]
This might've happened because the branch was already up-to-date with `master`, so there was nothing to commit after merging it into the PR's branch (https://github.com/paritytech/parity-processbot/blob/796d5105f5b608c19f33a934dcb2076993fd0d0c/src/git_ops.rs#L120-L121). In this case the error message should be improved to tell that fact.
